### ISSUE TITLE
Fix the All Contributors bot

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/wiki-mdbook#10]
### What Happened?

Fix the All Contributors bot & credit contributors to the project accordingly.

**Comment by Jarmos-san** [comment]
@all-contributors please add @Jarmos-san for code, infra, doc, tool, ideas, content, maintenance, projectManagement, review.

**Comment by Jarmos-san** [comment]
@Bhupesh-V I don't know how to fix the All-Contributors bot. You might've to help me on this regard :sweat_smile: 

These are the people who contributed wiki content (add more if I missed out some):

- @sggts04 for content, ideas
- @Bhupesh-V for review, content, ideas, projectManagement (add more if I missed out on some)
- and myself.

**Comment by Bhupesh-V** [comment]
@all-contributors please add @sggts04 for content, ideas

**Comment by Bhupesh-V** [comment]
@all-contributors please add @Bhupesh-V  for review, content, ideas, projectManagement

**Comment by Bhupesh-V** [comment]
@all-contributors please add @Jarmos-san for review, content, ideas, projectManagement, infra, tool, code

**Comment by Bhupesh-V** [comment]
@all-contributors please add @sggts04 for content, ideas
