### ISSUE TITLE
[REPORT]: Fix the All-Contributors issue

### ISSUE THREAD

**Issue by Jarmos-san** [developersIndia/wiki-mdbook#6]
### What Happened?

The All-Contributors bot's JSON configuration file is broken. This thread will be used as a scratch pad to fix it's issues.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarmos-san** [comment]
@all-contributors please add @sggts04 for content

**Comment by Jarmos-san** [comment]
@all-contributors please add @Jarmos-san for code, content, doc, ideas, infra, maintenance, projectManagement, review, tool.

**Comment by Jarmos-san** [comment]
@all-contributors please add @Bhupesh-V for code, review, tool, content.

**Comment by Bhupesh-V** [comment]
@Jarmos-san try to add contributors 1 by 1. Instead of creating all PRs at same time. Create one request then merge that PR

**Comment by Jarmos-san** [comment]
@all-contributors please add @Jarmos-san for code, infra, doc, tool, ideas, content, maintenance, projectManagement, review, tool.
